function wfobj = galvoSLMRaster
rangeV = [ -0.5204,    1.6481];
sweepTime = 0.5;
maxAccel = 20;
dt = 0.001;

% RAS Raster Scan
wfobj = GalvoSweeps(...
    'Nsweeps', 1, ...
    'rangeV', rangeV, ...
    'sweepTime', sweepTime, ...
    'maxAccel', maxAccel, ...
    'dt', dt);