function [waveform, blank_signal] = galvoTriangleWave(rangeV, sweepTime, maxAccel, dt)
    if isscalar(rangeV)
        % if range is a scalar the waveform is centered at zero
        offset = 0;
        range = rangeV;
    else
        offset = (rangeV(2) + rangeV(1)) / 2;
        range = rangeV(2) - rangeV(1);
    end
    tLinear = 0:dt:(ceil(sweepTime/dt)*dt);
    slope = range/sweepTime;
    vLinear = slope * tLinear - range/2;
    tTurnaround = dt:dt:(slope / maxAccel);
    vTurnaround = -maxAccel * tTurnaround.^2 / 2 + slope * tTurnaround;
    waveform = [-flip(vTurnaround(1:(end-1))) +  vLinear(1), ...
                vLinear, ...
                vTurnaround + vLinear(end), ...
                flip(vTurnaround(1:(end-1))) + vLinear(end), ...
                flip(vLinear),...
                -vTurnaround +  vLinear(1)] + offset;
    blank_signal = [...
        zeros(1, length(vTurnaround)-1),...
        ones(1, length(vLinear)),...
        zeros(1, 2*length(vTurnaround)-1),...
        ones(1, length(vLinear)),...
        zeros(1, length(vTurnaround))];
end
    